### ISSUE TITLE
Workload identity: `failed to retrieve Azure access token` on first call

### ISSUE THREAD

**Issue by rickardp** [grafana/azure-data-explorer-datasource#1250]
**What happened**:
* (Data source is provisioned)
* Go to Explore tab, choose the Azure Data Explorer data source
* Observe the following error
* 

![Image](https://github.com/user-attachments/assets/0478c6f2-c53e-4d50-99c4-0cf7bf82bfe9)
* Go to the Data sources tab
* Press "Save & Test" (without any changes)
* Observe a successful response
* Go back to Explore
* Observe the data source is working

If the data source is provisioned as read only, pressing the "Test" button will *not* work

**What you expected to happen**:
The data source working the first time

**How to reproduce it (as minimally and precisely as possible)**:
The following is the provisioning of the data source:
```yaml
...
- name: Data Explorer
          type: grafana-azure-data-explorer-datasource
          uid: adx
          isDefault: false
          jsonData:
            authType: workloadidentity
            clusterUrl: "$__env{ADX_CLUSTER}"
            defaultDatabase: my-database
          access: proxy
```
**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version: Grafana v11.5.2 (598e0338d5)
- Plugin version: 5.1.1
- OS Grafana is installed on: Official Docker image
- User OS & Browser: macOS, Safari
- Others:
