### ISSUE TITLE
Add documentation how to build this plugin

### ISSUE THREAD

**Issue by secustor** [grafana/azure-data-explorer-datasource#172]
As a first time contributor it has been a little bit tricky to find out the correct tools and order of execution.

I suggest to create Contributing.md to ease the start for new contributors.

For documentation purpose, this has been the steps I had to do to get the environment up: 
- Run `yarn` to install JS/TS dependencies
- Install [Mage](https://magefile.org/) 
- Build project
   - `mage -v buildAll`
   - `grafana-toolkit plugin:ci-build`
   - The built plugin is now in the `dist` folder
- E2E testing 
   - start a container on which you mount the folder `/var/lib/grafana` onto your host.
   - create a folder under `plugins` e.g `azure-data-explorer-testing`
   - copy the content of your `dist` folder into this folder. 
   - Restart the container. You should now have a unsigned version of the azure data explorer datasource, which you can add.

**Comment by brycefisher** [comment]
It can really save time to provision a data  source using the plugin too so you can test things out. Here's a minimal yaml file I got working:

```yaml
apiVersion: 1

datasources:
  - name: ADX
    type: grafana-azure-data-explorer-datasource
    access: proxy
    isDefault: true
    jsonData:
      clusterUrl: "https://yourcluster.eastus.kusto.windows.net"
      clientId: "<client ID GUID>"
      tenantId: "<tenant ID GUID>"
    secureJsonData:
      clientSecret: "<client secret>"
    version: 1
    editable: true
```
Obviously, you have to replace most of the values with whatever is correct for your azure environment.

Instead of the e2e testing instructions, I was able to use the existing docker-compose.yml file in this repo, then drop the above yaml file into _provisioning/datasources/adx.yml_ relative to the project root (which is automatically mounted into the container). This will allow you to have your plugin configured with authentication.

I also recommend setting these environment values in the docker-compose.yml file:

```
  environment:
    - TERM=linux
    - GF_DEFAULT_APP_MODE=development
    - GF_SECURITY_ADMIN_USER=adx
    - GF_SECURITY_ADMIN_PASSWORD=adx
```

Now, open your browser to http://localhost:300/, sign in with username/password of adx and you'll keep the browser session across docker container restarts.
