### ISSUE TITLE
Environment variables in data source provisioning files don't work with boolean properties

### ISSUE THREAD

**Issue by floushee** [grafana/azure-data-explorer-datasource#442]
**What happened**:
We use the adx plugin in multiple deployments. Sometimes we want to have on behalf of authentication and sometimes we don't. As we use Docker containers for the deployments we use env variables to inject settings into Grafana and its plugins as it is described [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables).

When we do that with the adx plugin, e.g:
```
datasources:
  - name: ...
    ...
    jsonData:
      clusterUrl: ...
      tenantId: ...
      clientId: ...
      onBehalfOf: $ADX_ON_BEHALF_OF
      oauthPassThru: $ADX_OAUTH_PASS_THRU
```
We get the following error messages:
"could not unmarshal DatasourceSettings json: json: cannot unmarshal string into Go struct field DatasourceSettings.oauthPassThru of type bool"

**What you expected to happen**:
We would expect that setting the env variables to true would enable the on behalf of authentication whereas false would disable it.

**How to reproduce it (as minimally and precisely as possible)**:
Just configure the two env variables and set the value to either true or false.

- Grafana version: 9.0.5
- Plugin version: 4.1.3
