### ISSUE TITLE
ADX plugin with AKS Workload Identity

### ISSUE THREAD

**Issue by mts-dyt** [grafana/azure-data-explorer-datasource#752]
**What happened**: Configure ADX data source with AKS Workload ID return error: `Post "https://<ADX_CLUSTER>.kusto.windows.net/v1/rest/query": failed to retrieve Azure access token: secret can't be empty string`

**What you expected to happen**: Test connection OK

**How to reproduce it (as minimally and precisely as possible)**:
- Configure grafana to use WorkloadID
- Check that AZURE secrets and variables are automatically mounted into grafana pods
- Add RBAC for Managed ID to access kusto cluster or DB
- Configure datasource to use workloadID:
```
- name: ADX
  type: grafana-azure-data-explorer-datasource
  access: proxy
  basicAuth: false
  editable: false
  jsonData:
    azureAuthType: workloadidentity
    clusterUrl: $ADX_CLUSTER
    tenantId: $ADX_TENANT
    defaultDatabase: $ADX_DATABASE
```

**Screenshots**
![image](https://github.com/grafana/azure-data-explorer-datasource/assets/105656094/b7213e05-6e14-464b-89bd-2144944dc448)

**Environment**:

- Grafana version: v10.2.2 
- Plugin version: 4.8.0
- OS Grafana is installed on: AKS
